---
title: "STAT 184 Final Project"
authors: "ProjectTeam 13-3"
date: "April 20, 2021"
output: html_notebook
---

#### Load Packages
```{r}
library(tidyverse)
library(data.table)
```

#### Read in Data and Convert Stat Files to Data Frames
```{r}
# Reads the .csv files
MemFantasy <-
  read.csv("Memorial_Fantasy.csv", header = TRUE)

PGAFantasy <-
  read.csv("PGA_Fantasy.csv", header = TRUE)

SchFantasy <-
  read.csv("Schwab_Fantasy.csv", header = TRUE)

# Reads in the .txt files for further changes
Mem_Start <-
  fread("Memorial_Stats.txt", header = TRUE)

PGA_Start <-
  fread("PGA_Stats.txt", header = TRUE)

Sch_Start <-
  fread("Schwab_Stats.txt", header = TRUE)

# Uses the "Start" to create a new table to tidy the data and add variable names
MemStats <-
  as.data.frame(matrix(Mem_Start$Data, ncol = 9, byrow = TRUE, dimnames = list(c(), c("Position", "Name", "Score", "PUTT", "ARG", "APP", "OTT", "T2G", "Total"))))
MemStats

PGAStats <-
  as.data.frame(matrix(PGA_Start$Data, ncol = 9, byrow = TRUE, dimnames = list(c(), c("Position", "Name", "Score", "PUTT", "ARG", "APP", "OTT", "T2G", "Total"))))
PGAStats

SchStats <-
  as.data.frame(matrix(Sch_Start$Data, ncol = 9, byrow = TRUE, dimnames = list(c(), c("Position", "Name", "Score", "PUTT", "ARG", "APP", "OTT", "T2G", "Total"))))
SchStats
```

#### Join Fantasy and Statistics to Create One Data Frame for Each of Three Tournaments
```{r}
MemFinal <-
  MemStats %>%
  inner_join(MemFantasy, by = "Name")
MemFinal

PGAFinal <-
  PGAStats %>%
  inner_join(PGAFantasy, by = "Name")
PGAFinal

SchFinal <-
  SchStats %>%
  inner_join(SchFantasy, by = "Name")
SchFinal
```

#### Combining the tables and getting score for all three tournaments for each player to get the avg
```{r}
TournamentsFinal <-
  rbind(MemFinal, PGAFinal, SchFinal)

Scores <- 
  TournamentsFinal %>%
  select(Name, Tournament, Score) %>%
  mutate(Score = gsub("E", 0, Score)) %>%
  mutate(Score = as.numeric(Score)) %>%
  spread(Tournament, Score)
Scores
```

#### Adding the final variables
```{r}
#Rank
TournamentsFinal <-TournamentsFinal%>%
  group_by(Tournament)%>%
  mutate(rank=rank(desc(Total),ties.method = "min"))


#Top10
TournamentsFinal <-TournamentsFinal%>%
  mutate(top10=ifelse(rank<=10,"yes","no"))

#MadeCut
TournamentsFinal <- TournamentsFinal %>%
  mutate(MadeCut = ifelse(grepl("CUT", Position), "No", "Yes"))

#Salary
TournamentsFinal <-TournamentsFinal%>%
  mutate(SalaryRange=ifelse(Salary>=6000 & Salary<7000 ,"6000s","7000s"))
TournamentsFinal <-TournamentsFinal%>%
  mutate(SalaryRange=ifelse(Salary>=7000 & Salary<8000 ,"7000s",SalaryRange))
TournamentsFinal <-TournamentsFinal%>%
  mutate(SalaryRange=ifelse(Salary>=8000 & Salary<9000 ,"8000s",SalaryRange))
TournamentsFinal <-TournamentsFinal%>%
  mutate(SalaryRange=ifelse(Salary>=9000 & Salary<10000,"9000s",SalaryRange))
TournamentsFinal <-TournamentsFinal%>%
  mutate(SalaryRange=ifelse(Salary>=10000 & Salary<11000 ,"10000s",SalaryRange))
TournamentsFinal <-TournamentsFinal%>%
  mutate(SalaryRange=ifelse(Salary>=11000 & Salary<12000,"11000s",SalaryRange))
  
#tournplayed
TournamentsFinal <-TournamentsFinal%>%
  group_by(Name)%>%
  mutate(tournplayed=n())
  
#Adding the scores for all the tournaments to each players name
TournamentsFinal <-
  TournamentsFinal %>%
  left_join(Scores, by = "Name")

#Avg
TournamentsFinal$avg <-
  round(rowMeans(TournamentsFinal[, c(19:21)], na.rm = TRUE), 1)

TournamentsFinal
```

